#!/usr/bin/env node
// One command after the recorded Bob run: every report the submission needs, the replay
// bundle for the deployed panel, and the exact numbers for the statements' [brackets].
// Everything is computed from the ledger, real scans and a real build. Nothing is typed in.

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import { join } from 'node:path'
import { readLedger } from '../chainguard/src/signalbox.js'
import { metrics, reduce } from '../chainguard/src/signalbox-state.js'

const root = execSync('git rev-parse --show-toplevel', { encoding: 'utf8' }).trim()
const run = (cmd, opts = {}) => execSync(cmd, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], ...opts })
const step = (msg) => console.log(`\n▸ ${msg}`)
const kb = (n) => `${Math.round(n / 1024)} kB`
const dur = (ms) => (ms >= 3600e3 ? `${Math.floor(ms / 3600e3)} h ${Math.round((ms % 3600e3) / 60e3)} min` : `${Math.max(1, Math.round(ms / 60e3))} min`)

const events = readLedger(root)
const state = reduce(events)
if (!state) {
  console.error('No signal box ledger found (.signalbox/ledger.jsonl). Run the Bob migration first (docs/BOB_RUNBOOK.md).')
  process.exit(1)
}
const m = metrics(events)
const warnings = []
if (m.cleared < m.blocks) warnings.push(`${m.blocks - m.cleared} block(s) not cleared yet`)

step('Legacy scan (guard)')
let guardOk = true
try { run('node chainguard/bin/chainguard.js scan legacy-dapp/src --fail-on warning') } catch { guardOk = false; warnings.push('npm run guard fails: legacy call sites remain') }
const scan = JSON.parse(run('node chainguard/bin/chainguard.js scan legacy-dapp/src --format json'))
const base = JSON.parse(readFileSync(join(root, 'reports/baseline.json'), 'utf8'))
console.log(`  ${base.totals.findings} → ${scan.totals.findings} legacy call sites`)

step('Behavior tests')
let tests = ''
try { tests = run('npm test --prefix legacy-dapp').split('\n').find((l) => /^\s*Tests\s+/.test(l))?.trim() || 'passed' } catch (e) { tests = 'FAILED'; warnings.push('legacy-dapp tests fail') }
const testsChanged = run('git diff --name-only before-bob -- "legacy-dapp/src/**/__tests__/**" 2>/dev/null || true').trim()
if (testsChanged) warnings.push(`test files changed since before-bob: ${testsChanged.split('\n').join(', ')}`)
console.log(`  ${tests}${testsChanged ? ' (TEST FILES CHANGED)' : ', test files unchanged'}`)

step('Production build and bundle size')
let bundle = null
try {
  run('npm run build --prefix legacy-dapp')
  const dir = join(root, 'legacy-dapp/dist/assets')
  let raw = 0
  let gz = 0
  for (const f of readdirSync(dir).filter((f) => /\.(js|css)$/.test(f))) {
    const b = readFileSync(join(dir, f))
    raw += b.length
    gz += gzipSync(b, { level: 9 }).length
  }
  const before = JSON.parse(readFileSync(join(root, 'reports/baseline-bundle.json'), 'utf8'))
  bundle = { before: before.gzipBytes, after: gz, raw, change: Math.round((1 - gz / before.gzipBytes) * 100) }
  console.log(`  ${kb(bundle.before)} → ${kb(bundle.after)} gzip (−${bundle.change}%)`)
} catch { warnings.push('legacy-dapp build fails') }
const pkg = JSON.parse(readFileSync(join(root, 'legacy-dapp/package.json'), 'utf8'))
const stillLegacy = ['ethers', 'web3'].filter((d) => pkg.dependencies?.[d])
if (stillLegacy.length) warnings.push(`still in package.json: ${stillLegacy.join(', ')} (runbook step 4)`)

step('Reports')
run('node chainguard/bin/signalbox.js report --out reports/signalbox-report.md')
writeFileSync(join(root, 'reports/signalbox-log.txt'), run('node chainguard/bin/signalbox.js log'))
run('node chainguard/bin/chainguard.js scan legacy-dapp/src --baseline reports/baseline.json --format md --out reports/after.md')
console.log('  reports/signalbox-report.md, reports/signalbox-log.txt, reports/after.md')

step('Replay bundle for the deployed panel')
run('npm run -s atlas')
console.log('  atlas/src/data/atlas-data.json, atlas/src/data/ledger.json, atlas/dist')

const fault = events.find((e) => e.t === 'verify' && !e.ok && !e.checks.tests.ok)
const faultExample = fault ? `${fault.task}: ${(fault.checks.tests.failures?.[0] || fault.checks.tests.summary || '').replace(/^(×|✗|FAIL)\s+/, '').replace(/\s+\d+ms$/, '')}` : 'none'
const numbers = [
  '# Submission numbers',
  '',
  `Generated by \`npm run finalize\` on ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC from the ledger, real scans and a real build.`,
  'Paste these into the [brackets] in docs/submission/*.md, then recount the words (limit 500).',
  '',
  '| Placeholder | Value |',
  '| --- | --- |',
  `| Legacy call sites | ${base.totals.findings} → ${scan.totals.findings} |`,
  `| Files on legacy APIs | ${base.filesAffected} / ${base.filesScanned} → ${scan.filesAffected} / ${scan.filesScanned} |`,
  `| Blocks cleared | ${m.cleared} / ${m.blocks} in ${m.waves} waves |`,
  `| Bob subagents / peak in parallel | ${m.agents.length} / ${m.peakParallel} |`,
  `| Faults caught before commit | ${m.faults} (scope ${m.faultsByCheck.scope}, contract ${m.faultsByCheck.contract}, scan ${m.faultsByCheck.scan}, tests ${m.faultsByCheck.tests}) |`,
  `| Example fault | ${faultExample} |`,
  `| SPADs / rollbacks / refused claims | ${m.spads} / ${m.rollbacks} / ${m.denied} |`,
  `| Blocks cleared on the first release | ${m.firstTimeRight} / ${m.cleared} |`,
  `| Behavior tests | ${tests}${testsChanged ? ' (test files changed!)' : ', unmodified'} |`,
  `| Bundle (gzip) | ${bundle ? `${kb(bundle.before)} → ${kb(bundle.after)} (−${bundle.change}%)` : 'build failed'} |`,
  `| Wall clock, box opened → last clear | ${dur(m.wallClockMs)} |`,
  '',
  warnings.length ? `## Warnings\n\n${warnings.map((w) => `- ${w}`).join('\n')}\n` : '## Warnings\n\nNone. Ready to submit.\n',
].join('\n')
writeFileSync(join(root, 'reports/submission-numbers.md'), numbers)

step('Done')
console.log(numbers.split('\n').slice(5).join('\n'))
console.log(`Commit and deploy:
  git add .signalbox/ledger.jsonl reports/ atlas/src/data/ bob_sessions/
  git commit -m "Finalize: Bob run reports and replay"
  git push   # then merge to main; the Pages workflow deploys the panel`)
process.exitCode = warnings.length ? 1 : 0
